### ISSUE TITLE
Haiku application generated form the workload template fails on loading BApplication

### ISSUE THREAD

**Issue by nx6-archived** [trungnt2910/dotnet-haiku#18]
`dotnet build` succeeds with no warnings or errors but running the application executable or via `dotnet run`, return the following error:

```
Unhandled exception. System.TypeLoadException: Could not load type 'Haiku.App.BApplication' from assembly 'haiku, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Abort
```
[haiku.zip](https://github.com/trungnt2910/dotnet-haiku/files/13849898/haiku.zip)

Please find attached the project generated out of the template.

**Comment by trungnt2910** [comment]
Can you please name the project something other than `haiku` (case-insensitive)?

I can see in the zip file, there are two different `.dll`s, a large `Haiku.dll` (which is what I named in my workload), and a smaller `haiku.dll` (which is probably what you have recently built). I am not sure; I don't have my development machine right now and can't access a .NET decompiler.

What is happening might be that .NET `.dll` resolution is case-insensitive to match with Windows platform conventions. Whatever strategy the runtime is using might have found `haiku.dll` before `Haiku.dll`, and tried resolving `BApplication` from there instead.

**Comment by nx6-archived** [comment]
Good spot! I've renamed it to HaikuApp and it started. I've found some relative old issues around 2020 discussing case sensitivity on file systems like APFS, I'm wondering if that has been solved and the sdk/runtime can be configured for a case-sensitive file system.

**Comment by trungnt2910** [comment]
Closing for now, name clashes with system binaries is undesirable regardless of the platform, and on Haiku `Haiku.*` should be reserved.

**Comment by trungnt2910** [comment]
Closing for now, name clashes with system binaries is undesirable regardless of the platform, and on Haiku `Haiku.*` should be reserved.
